Create database DTDD
use DTDD

CREATE TABLE NHACUNGCAP(
	[MaNCC] [nvarchar](20) PRIMARY KEY NOT NULL,
	[TenNCC] [nvarchar](200) NOT NULL,
	[DiaChiNCC] [nvarchar](200),
	[SDTNCC] [nvarchar](10),
)

CREATE TABLE HOADONNHAP(
	[SoHDN] [nvarchar](20) PRIMARY KEY NOT NULL,
	[MaNCC] [nvarchar](20) REFERENCES NHACUNGCAP(MaNCC)NOT NULL,
	[MaNV] [nvarchar](20)  REFERENCES NHANVIEN(MaNV) NOT NULL,
	[NgayNhap] [datetime] NOT NULL,
	[TongTien] [money],
)

CREATE TABLE NHANVIEN(
	[MaNV] [nvarchar](20) PRIMARY KEY NOT NULL,
	[MaCV] [nvarchar](20) REFERENCES CHUCVU(MaCV) NOT NULL,
	[TenNV] [nvarchar](100)  NOT NULL,
	[SDTNV] [nvarchar](20)  NOT NULL,
	[GioiTinh] [nvarchar](20),
	[DiaChiNV] [nvarchar](200),
	[NgaySinh] [datetime],
)

CREATE TABLE CHUCVU(
	[MaCV] [nvarchar](20) PRIMARY KEY NOT NULL,
	[TenCV] [nvarchar](100) NOT NULL,
)

CREATE TABLE TAIKHOAN(
	[UserID] [nvarchar](20) PRIMARY KEY NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[SDTUser] [nvarchar](10) NOT NULL,
	[DiaChiUser] [nvarchar](200) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
)

CREATE TABLE HOADONBAN(
	[SoHDB] [nvarchar](20) PRIMARY KEY NOT NULL,
	[MaNV] [nvarchar](20) REFERENCES NHANVIEN(MaNV) NOT NULL,
	[UserID] [nvarchar](20) REFERENCES TAIKHOAN(UserID) NOT NULL,
	[NgayBan] [datetime] NOT NULL,
	[TongTien] [money],
)

CREATE TABLE CHITIETHDB(
	[MaHDB] [nvarchar](20) PRIMARY KEY NOT NULL,
	[SoHDB] [nvarchar](20) REFERENCES HOADONBAN(SoHDB) NOT NULL,
	[KhuyenMai] [money],
	[SLBan] [int] NOT NULL,
)

CREATE TABLE HANG(
	[MaHangSX] [nvarchar](20) PRIMARY KEY NOT NULL,
	[TenHangSX] [nvarchar](100) NOT NULL,
)

CREATE TABLE DONDATHANG
(
	[MaDH] NVARCHAR(20) NOT NULL PRIMARY KEY, 
    [MaNV] NVARCHAR(20) NOT NULL, 
    [UserID] NVARCHAR(20) NOT NULL, 
    [NgayDat] DATE NOT NULL, 
    [NgayGiao] DATE NOT NULL, 
    [TongTien] MONEY NOT NULL, 
    [TongThanhToan] MONEY NOT NULL, 
    CONSTRAINT [FK_DONDATHANG_NHANVIEN] FOREIGN KEY (MaNV) REFERENCES [NHANVIEN](MaNV), 
    CONSTRAINT [FK_DONDATHANG_USER] FOREIGN KEY (UserID) REFERENCES [TAIKHOAN](UserID)
)

CREATE TABLE CHITIETDDH
(
	[MaDT] NVARCHAR(20) NOT NULL, 
    [MaDH] NVARCHAR(20) NOT NULL, 
    [KhuyenMai] MONEY NOT NULL, 
    [SLDat] INT NOT NULL, 
    CONSTRAINT [FK_CHITIETDDH_DIENTHOAI] FOREIGN KEY (MaDT) REFERENCES [DIENTHOAI](MaDT), 
    CONSTRAINT [FK_CHITIETDDH_DONDATHANG] FOREIGN KEY (MaDH) REFERENCES [DONDATHANG](MaDH) 
)

CREATE TABLE CHITIETHDN
(
	[MaDT] NVARCHAR(20) NOT NULL, 
    [SoDHN] NVARCHAR(20) NOT NULL, 
    [KhuyenMai] MONEY NOT NULL, 
    [SLNhap] INT NOT NULL, 
    CONSTRAINT [FK_CHITIETHDN_DIENTHOAI] FOREIGN KEY (MaDT) REFERENCES [DIENTHOAI](MaDT)
)

CREATE TABLE DIENTHOAI
(
	[MaDT] NVARCHAR(20) NOT NULL PRIMARY KEY, 
    [MaHangSX] NVARCHAR(20) NOT NULL, 
    [TenDT] NVARCHAR(100) NOT NULL, 
    [DonGiaBan] MONEY NOT NULL, 
    [SoLuong] INT NOT NULL, 
    [DonGiaNhap] MONEY NOT NULL, 
    [MieuTa] NTEXT NOT NULL, 
    [Ram] NVARCHAR(100) NOT NULL, 
    [Rom] NVARCHAR(100) NOT NULL, 
    [MauSac] NVARCHAR(50) NOT NULL, 
    [CPU] NVARCHAR(100) NOT NULL, 
    [ThoiGianBH] INT NOT NULL, 
    [DLPin] NVARCHAR(50) NOT NULL, 
    [TrongLuong] FLOAT NOT NULL, 
    [TenFileAnh] VARCHAR(50) NOT NULL, 
    [DanhGia] NTEXT NOT NULL, 
    CONSTRAINT [FK_DIENTHOAI_HANG] FOREIGN KEY (MaHangSX) REFERENCES [HANG](MaHangSX),
)


CREATE TABLE CHITIETANH
(
	[MaDT] NVARCHAR(20) NOT NULL, 
    [TenFileAnh] VARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_CHITIETANH_DIENTHOAI] FOREIGN KEY (MaDT) REFERENCES [DIENTHOAI](MaDT) 
)